version: "3.9"

networks:
    laravel:
        name: laravel

services:

    nginx_bu:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - php_bu
            - mysql_bu
        container_name: nginx_bu
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    php_bu:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php_bu
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    mysql_bu:
        image: mysql:8.0.27
        container_name: mysql_bu
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
        networks:
            - laravel

    composer_bu:
        image: composer:latest
        container_name: composer_bu
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    artisan_bu:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan_bu
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']
        networks:
            - laravel

    npm_bu:
        image: node:current-alpine
        container_name: npm_bu
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel







